### ISSUE TITLE
Unable to build after clean install.

### ISSUE THREAD

**Issue by AhmedSamara** [charlesrwest/QRCodeStateEstimation#1]
I tried this too different ways, first by running `cmake .` in the root directory, and also by creating a `build` directory and running `cmake ..`,

and then running `make`. It gets to 100% and then I get this error:

```
[100%] Linking CXX executable ../../bin/estimateLocationFromQRCode
/usr/bin/ld: CMakeFiles/estimateLocationFromQRCode.dir/main.cpp.o: undefined reference to symbol '_ZN2cv12VideoCaptureD1Ev'
/usr/local/lib/libopencv_videoio.so.3.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
src/example/CMakeFiles/estimateLocationFromQRCode.dir/build.make:95: recipe for target 'bin/estimateLocationFromQRCode' failed
make[2]: *** [bin/estimateLocationFromQRCode] Error 1
CMakeFiles/Makefile2:161: recipe for target 'src/example/CMakeFiles/estimateLocationFromQRCode.dir/all' failed
make[1]: *** [src/example/CMakeFiles/estimateLocationFromQRCode.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

The full output of the command is on [this gist](https://gist.github.com/AhmedSamara/2187040a82925683c218).

I've run into this problem before, and maybe I just don't know how to use make files, but I'm not sure how to get around it.

**Comment by AhmedSamara** [comment]
Nevermind, fixed it by re-installing OpenCV from the dnf package manager instead of trying to build it.

This doesn't explain why i got this error while trying to install OpenCV, but that's an issue for another repo.

**Comment by AhmedSamara** [comment]
Just kidding, I'm still unable to rebuild.

It seemed the error from before was that I didn't have opencv, but now it looks like it can't identify opencv functions, so maybe there are issues with the import?

```
../../lib/libQRCodeStateEstimation.so: undefined reference to `cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
../../lib/libQRCodeStateEstimation.so: undefined reference to `cv::String::allocate(unsigned long)'
../../lib/libQRCodeStateEstimation.so: undefined reference to `cv::String::deallocate()'
../../lib/libQRCodeStateEstimation.so: undefined reference to `cv::namedWindow(cv::String const&, int)'
../../lib/libQRCodeStateEstimation.so: undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
collect2: error: ld returned 1 exit status
src/example/CMakeFiles/estimateLocationFromQRCode.dir/build.make:95: recipe for target 'bin/estimateLocationFromQRCode' failed
make[2]: *** [bin/estimateLocationFromQRCode] Error 1
CMakeFiles/Makefile2:161: recipe for target 'src/example/CMakeFiles/estimateLocationFromQRCode.dir/all' failed
make[1]: *** [src/example/CMakeFiles/estimateLocationFromQRCode.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by charlesrwest** [comment]
Did you run cmake again after switching to the repo version?  Try that.  You may also want to delete the CMakeCache.txt file and then run CMake again to make sure it doesn't have any stale references.

I just recloned the code and compiled on my Ubuntu machine and it worked fine, so the packages should still work OK.  Please post if that doesn't resolve the issue.

Thanks,
Charlie

**Comment by AhmedSamara** [comment]
I deleted the entire repo and tried again, still the same error.

I'm on fedora22 and I believe that may be causing this.

**Comment by charlesrwest** [comment]
Alright.  I just removed my repo copies of opencv from my machine and compiled Opencv 3.0 from source.  It appears that the issue was that 3.0 broke the video display/retrieval functionality into a separate module (videoio) and that was what was breaking the build.

I've fixed a version of the library so that it will work with Opencv 3.0 (which is probably what the Fedora package is) and added it to a branch OpenCV3-0Compatible.  Try checking out that branch and let me know whether it works for you.

Thanks,
Charlie

**Comment by AhmedSamara** [comment]
It did not, I still get this error:

I checked what version of OpenCV I had and it's 2.4 so that's not it.

```
../../lib/libQRCodeStateEstimation.so: undefined reference to `cv::namedWindow(cv::String const&, int)'
../../lib/libQRCodeStateEstimation.so: undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
collect2: error: ld returned 1 exit status
src/example/CMakeFiles/estimateLocationFromQRCode.dir/build.make:95: recipe for target 'bin/estimateLocationFromQRCode' failed
make[2]: *** [bin/estimateLocationFromQRCode] Error 1
CMakeFiles/Makefile2:161: recipe for targ
```

**Comment by charlesrwest** [comment]
Well, if you tried compiling from source again the 3.0 version might work for you.  Otherwise, it looks like you are having trouble linking to highgui or there has been an interface change.  If you don't care about seeing the output, you should be able to comment out the two lines that use those two functions without hurting anything except for the option of showing a display window.

Alternatively, I could try to either setup a virtual machine or install fedora on an old laptop (maybe this weekend, if there is time?) or we could arrange to meet in my lab and I could try to fix it on your machine.
